/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#16351d",
        "deep-forest": "#1A2E1D",
        "on-primary": "#ffffff",
        "primary-container": "#2d4c32",
        "on-primary-container": "#99bc9a",
        "secondary": "#516446",
        "secondary-container": "#d1e6c1",
        "on-secondary-container": "#56684a",
        "tertiary": "#1e3421",
        "tertiary-container": "#344b36",
        "surface": "#fcf9f3",
        "sacred-palace": "#F9F6F0",
        "surface-container": "#f0eee8",
        "surface-container-low": "#f6f3ed",
        "surface-container-high": "#ebe8e2",
        "surface-container-highest": "#e5e2dc",
        "on-surface": "#1c1c18",
        "on-surface-variant": "#424841",
        "gold-leaf": "#C5A059",
        "olive-drab": "#4B5320",
        "moss-shadow": "#3E4C33",
        "outline": "#727971",
        "outline-variant": "#c2c8bf",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
      },
      fontFamily: {
        display: ['Playfair Display', 'serif'],
        headline: ['Playfair Display', 'serif'],
        body: ['Open Sans', 'sans-serif'],
        label: ['Montserrat', 'sans-serif'],
      },
      spacing: {
        'gutter-sm': '16px',
        'gutter-lg': '24px',
        'margin-mobile': '20px',
        'margin-desktop': '80px',
        'container-max': '1360px',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'sm': '0.125rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
    },
  },
  plugins: [],
};
